---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: show-sbom
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "konflux"
spec:
  description: >-
    Shows the Software Bill of Materials (SBOM) generated for the built image in CyloneDX JSON format.
  params:
    - name: IMAGE_URL
      description: Fully qualified image name to show SBOM for.
      type: string
    - name: PLATFORM
      description: Specific architecture to display the SBOM for. An example arch would be "linux/amd64". If IMAGE_URL
        refers to a multi-arch image and this parameter is empty, the task will default to use "linux/amd64".
      type: string
      default: "linux/amd64"
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from.
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data.
      default: ca-bundle.crt
  steps:
  - name: show-sbom
    image: quay.io/konflux-ci/appstudio-utils:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9@sha256:24179f0efd06c65d16868c2d7eb82573cce8e43533de6cea14fec3b7446e0b14
    # per https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
    # the cluster will set imagePullPolicy to IfNotPresent
    env:
    - name: IMAGE_URL
      value: $(params.IMAGE_URL)
    - name: PLATFORM
      value: $(params.PLATFORM)
    script: |
      #!/bin/bash

      ca_bundle=/mnt/trusted-ca/ca-bundle.crt
      if [ -f "$ca_bundle" ]; then
        echo "INFO: Using mounted CA bundle: $ca_bundle"
        cp -vf $ca_bundle /etc/pki/ca-trust/source/anchors
        update-ca-trust
      fi

      download_sbom_with_retry() {
        status=-1
        max_try=5
        wait_sec=2

        PLATFORM_ARG="$1"
        for run in $(seq 1 $max_try); do
          status=0
          cosign download sbom $PLATFORM_ARG $IMAGE_URL 2>>err
          status=$?
          if [ "$status" -eq 0 ]; then
            break
          fi
          sleep $wait_sec
        done
        if [ "$status" -ne 0 ]; then
          echo "Failed to get SBOM after ${max_try} tries" >&2
          cat err >&2
        fi
      }

      RAW_OUTPUT=$(skopeo inspect --no-tags --raw docker://${IMAGE_URL})
      if [ $(jq -r '.mediaType' <<< $RAW_OUTPUT) == "application/vnd.oci.image.manifest.v1+json" ] ; then
        ARCHES=""
      else
        # Multi arch
        ARCHES=$(jq -r '.manifests[].platform.architecture' <<< $RAW_OUTPUT)
      fi

      if [ -z "${ARCHES}" ] ; then
        # single arch image
        download_sbom_with_retry ""
      else
        download_sbom_with_retry " --platform=$PLATFORM "
      fi
    volumeMounts:
    - name: trusted-ca
      mountPath: /mnt/trusted-ca
      readOnly: true
  volumes:
  - name: trusted-ca
    configMap:
      name: $(params.caTrustConfigMapName)
      items:
        - key: $(params.caTrustConfigMapKey)
          path: ca-bundle.crt
      optional: true
