  pipelineSpec:
    description: Simple pipeline to test Pulp Access Controller
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    tasks:
    - name: use-pulp-secret
      taskSpec:
        steps:
        - name: mount-and-display
          image: registry.access.redhat.com/ubi8/ubi-minimal:latest
          volumeMounts:
          - name: pulp-creds
            mountPath: /mnt/pulp-creds
          script: |
            echo "Listing files in /mnt/pulp-creds:"
            ls -la /mnt/pulp-creds
            
            echo -e "\nContents of tls.crt:"
            cat /mnt/pulp-creds/tls.crt
            
            echo -e "\nContents of tls.key:"
            cat /mnt/pulp-creds/tls.key
            
            echo -e "\nSecret mounted and accessed successfully!"
        volumes:
        - name: pulp-creds
          secret:
            secretName: pulp-access