apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/YasenT/testrepo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  labels:
    appstudio.openshift.io/application: test
    appstudio.openshift.io/component: testrepo-f7887
    pipelines.appstudio.openshift.io/type: build
  name: testrepo-f7887-on-pull-request
  namespace: ytrahnov-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  pipelineSpec:
    description: Simple pipeline to test Pulp Access Controller
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    tasks:
    - name: create-pulp-access-request
      taskSpec:
        steps:
        - name: kubectl-apply
          image: quay.io/openshift/origin-cli:latest
          script: |
            kubectl auth whoami
            kubectl auth can-i create pulpaccessrequests.pulp.konflux-ci.dev
            kubectl auth can-i get pulpaccessrequests.pulp.konflux-ci.dev
            kubectl auth can-i list pulpaccessrequests.pulp.konflux-ci.dev
            
    - name: use-pulp-secret
      runAfter:
      - create-pulp-access-request
      taskSpec:
        steps:
        - name: mount-and-display
          image: registry.access.redhat.com/ubi8/ubi-minimal:latest
          volumeMounts:
          - name: pulp-creds
            mountPath: /mnt/pulp-creds
          script: |
            echo "Listing files in /mnt/pulp-creds:"
            ls -la /mnt/pulp-creds
            
            echo -e "\nContents of tls.crt:"
            cat /mnt/pulp-creds/tls.crt
            
            echo -e "\nContents of tls.key:"
            cat /mnt/pulp-creds/tls.key
            
            echo -e "\nSecret mounted and accessed successfully!"
        volumes:
        - name: pulp-creds
          secret:
            secretName: pulp-access